INSERT INTO sys_majors (id,name_th,name_en) VALUES (10608,'วิศวกรรมคอมพิวเตอร์','Computer Engineering');
INSERT INTO sys_majors (id,name_th,name_en) VALUES (10610,'วิศวกรรมระบบสารสนเทศและเครือข่าย','Information Systems and Network Engineering');

INSERT INTO sys_category_types (name_th,name_en,short_name) VALUES ('หมวดวิชาศึกษาทั่วไป','General Education','GE');
INSERT INTO sys_category_types (name_th,name_en,short_name) VALUES ('หมวดวิชาเฉพาะ','Field of Specialization','FS');
INSERT INTO sys_category_types (name_th,name_en,short_name) VALUES ('หมวดวิชาเลือกเสรี','Free Electives','FE');
INSERT INTO sys_category_types (name_th,name_en,short_name) VALUES ('วิชาเอก','Major','Major');
INSERT INTO sys_category_types (name_th,name_en,short_name) VALUES ('วิชาโท','Minor','Minor');
INSERT INTO sys_category_types (name_th,name_en,short_name) VALUES ('ประสบการณ์ภาคสนาม','Field Experience Training','FET');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('หลักสูตร','Curriculum');

INSERT INTO sys_curricula (major_id,name_th,short_name) VALUES (10608,'หลักสูตรวิศวกรรมคอมพิวเตอร์ หลักสูตรปรับปรุง 2563','CPE63');

INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Total',1,true,143,7,true,'-','-','หมายเหตุ ได้มีการจัดอบรมเตรียมความพร้อมให้แก่นักศึกษาก่อนไปสหกิจศึกษา จำนวนไม่น้อยกว่า 30 ชั่วโมง');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('General Education',1,false,30,1,true,'#A78C39','#FFF8E2','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Field of Specialization',1,true,103,2,true,'#4351CC','#E7EAFF','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Free Electives',1,true,6,3,true,'#505152','#EBEAEA','Any courses can be selected with the approval from the student’s academic advisor.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Required Courses',1,false,23,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Learner Person',1,false,15,NULL,true,'#F0C32F','#FFF8E2','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Innovative Co-creator',1,false,4,NULL,true,'#F67F4C','#FFEBE3','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Active Citizen',1,false,4,NULL,true,'#BF504D','#EDDCDC','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Elective from 3 Categories',1,false,7,NULL,true,'#A37358','#F5E5DE','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'3 credits must be selected from the following courses');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'3 credits must be selected from the following courses');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Learner Person',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Innovative Co-creator',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Active Citizen',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Core Courses',1,false,33,NULL,true,'#3BA3EE','#E5F4FD','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.2 Major',1,true,70,4,'Required courses in 2.2.1 and 2.2.2 must have at least 36 credit hours for course id in 300 and 400 categories with at least 18 credit hours for course id in 400 category.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Required Courses',1,false,52,NULL,true,'#4351CC','#E7EAFF','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Major Electives',1,true,18,NULL,true,'#4351CC','#E7EAFF','There must be at least 9 credits from 261xxx.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Required Courses',1,false,58,NULL,true,'#4351CC','#E7EAFF','');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,is_display,primary_color,secondary_color,note) VALUES ('Major Electives',1,true,12,NULL,true,'#4351CC','#E7EAFF','There must be at least 9 credits from 261xxx.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Technology for Application',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Technology and Software Methods',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Basic Structure of the Systems',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Hardware and Computer Architecture',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Field Experience Training',1,NULL,NULL,6,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Field Experience Training',1,NULL,NULL,6,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Minor (if any)',1,true,15,5,'According to the Chiang Mai University regulation on the Minor curriculum for the Chiang Mai University student, if students choose to have a minor degree in a curriculum at the Chiang Mai university, they can register those courses not less than 15 credits with the academic advisor’s approval. Hence, the total credits for the whole curriculum is increased at least 15 credits.');

INSERT INTO sys_curriculum_questions (curriculum_id,name_en) VALUES (1,'Plan');

INSERT INTO sys_curriculum_question_choices (question_id,position,name_en) VALUES (1,1,'Normal Plan');
INSERT INTO sys_curriculum_question_choices (question_id,position,name_en) VALUES (1,2,'Cooperative Education Plan');

INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (1,2,NULL,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (1,3,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (1,4,NULL,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (2,5,NULL,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (5,6,NULL,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (5,7,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (5,8,true,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (2,9,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (6,10,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (6,11,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (7,12,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (7,13,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (9,14,false,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (9,15,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (9,16,false,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (3,17,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (3,18,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,19,NULL,1,1,1);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,20,NULL,2,1,1);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,21,NULL,1,1,2);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,22,NULL,2,1,2);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,23,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,24,true,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,25,true,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,26,true,4,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,23,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,24,true,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,25,true,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,26,true,4,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,27,true,5,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (20,28,false,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (20,29,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (22,28,false,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (22,29,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (3,30,NULL,3,NULL,NULL);

INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (18,'^...(3|4)..$',36);
INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (18,'^...4..$',18);
INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (20,'^261...$',9);
INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (22,'^261...$',9);

INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (10, '001101', 1, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (10, '001102', 2, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (10, '001201', 1, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (3, '001101', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (3, '001102', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (10, '001225', 2, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (4, '001101', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (4, '001102', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (11, '204100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (11, '261111', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (11, '953111', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (12, '259192', 2, 4, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '013110', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '050106', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '176100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '201114', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '201117', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '201190', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '207109', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '207110', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '368100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '602201', NULL, NULL, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '610111', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '703103', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '751100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '851103', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (13, '852100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (8, '140104', 1, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (8, '259191', 1, 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '201100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '203100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '211100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '462130', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '571116', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '701181', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '702101', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (14, '705191', NULL, NULL, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (15, '259194', NULL, NULL, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '011100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '109114', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '127100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '128100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '154104', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '254182', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '256131', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '259108', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '259193', NULL, NULL, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '259195', NULL, NULL, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '602102', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '801100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (16, '951100', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '206161', 1, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '206162', 2, 1, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (49, '206161', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '206261', 1, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (50, '206162', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '207105', 1, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '207106', 2, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '207115', 1, 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '207116', 2, 1, 1);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (54, '207115', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '252281', 2, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '259104', 1, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '259106', 1, 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '261208', 2, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (58, '206261', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '261216', 1, 2, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (17, '261306', 2, 3, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (60, '206261', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (23, '261405', 2, 4, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (61, '261361', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (23, '261491', 1, 4, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (23, '261492', 2, 4, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (63, '261491', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (24, '261102', 2, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (24, '261200', 2, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (65, '261102', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (65, '269102', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (24, '261217', 1, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (66, '261102', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (24, '261218', 2, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (67, '261216', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (67, '261217', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (24, '261361', 2, 3, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (68, '261200', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261103', 1, 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261207', 1, 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (70, '261103', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261332', 2, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (71, '207106', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261335', 1, 3, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (72, '261332', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (72, '269130', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261336', 1, 3, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261342', 1, 3, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (74, '261205', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (74, '261218', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (25, '261343', 1, 3, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (26, '261210', 1, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (76, '207106', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (26, '261212', 1, 2, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (26, '261214', 2, 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (78, '261210', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (78, '252281', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (26, '261215', 2, 2, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (26, '261304', 1, 3, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (80, '261214', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (26, '261305', 2, 3, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (81, '261304', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (81, '269210', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (27, '261495', 3, 3, 6);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261381', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261382', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261383', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261404', NULL, NULL, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (86, '261200', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261406', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (87, '261102', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261407', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (88, '261218', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261408', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261409', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (90, '261216', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (90, '261217', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261411', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261414', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (92, '261210', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261421', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (93, '261214', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (93, '261304', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261424', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261430', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261433', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (96, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261434', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (97, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261435', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (98, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261437', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (99, '261306', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (99, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261438', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (100, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261439', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261441', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261444', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (103, '261342', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261446', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (104, '261205', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (104, '261217', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261447', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (105, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261448', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261449', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (107, '261361', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261453', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261456', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261457', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261458', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261459', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261461', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (113, '261102', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (113, '269102', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (113, '229223', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261465', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (114, '259104', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261468', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261469', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261470', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261471', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261472', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261473', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261475', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261476', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (122, '252211', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (122, '252281', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261478', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261479', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261481', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261482', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261493', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261494', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261497', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261498', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '261499', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269421', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (132, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269430', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (133, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269431', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (134, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269432', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (135, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269433', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (136, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269441', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269461', NULL, NULL, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (28, '269462', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (139, '261361', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year, credit) VALUES (29, '261400', NULL, NULL, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (140, '261335', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (140, '261342', 'All');

INSERT INTO organizations (id, name_th, name_en) VALUES (00, 'มหาวิทยาลัยเชียงใหม่', 'Chiang Mai University');
INSERT INTO organizations (id, name_th, name_en) VALUES (01, 'คณะมนุษยศาสตร์', 'Faculty of Humanities');
INSERT INTO organizations (id, name_th, name_en) VALUES (02, 'คณะศึกษาศาสตร์', 'Faculty of Education');
INSERT INTO organizations (id, name_th, name_en) VALUES (03, 'คณะวิจิตรศิลป์', 'Faculty of Fine Arts');
INSERT INTO organizations (id, name_th, name_en) VALUES (04, 'คณะสังคมศาสตร์', 'Faculty of Social Sciences');
INSERT INTO organizations (id, name_th, name_en) VALUES (05, 'คณะวิทยาศาสตร์', 'Faculty of Science');
INSERT INTO organizations (id, name_th, name_en) VALUES (06, 'คณะวิศวกรรมศาสตร์', 'Faculty of Engineering');
INSERT INTO organizations (id, name_th, name_en) VALUES (07, 'คณะแพทยศาสตร์', 'Faculty of Medicine');
INSERT INTO organizations (id, name_th, name_en) VALUES (08, 'คณะเกษตรศาสตร์', 'Faculty of Agriculture');
INSERT INTO organizations (id, name_th, name_en) VALUES (09, 'คณะทันตแพทยศาสตร์', 'Faculty of Dentistry');
INSERT INTO organizations (id, name_th, name_en) VALUES (10, 'คณะเภสัชศาสตร์', 'Faculty of Pharmacy');
INSERT INTO organizations (id, name_th, name_en) VALUES (11, 'คณะเทคนิคการแพทย์', 'Faculty of Associated Medical Sciences');
INSERT INTO organizations (id, name_th, name_en) VALUES (12, 'คณะพยาบาลศาสตร์', 'Faculty of Nursing');
INSERT INTO organizations (id, name_th, name_en) VALUES (13, 'คณะอุตสาหกรรมเกษตร', 'Faculty of Agro-Industry');
INSERT INTO organizations (id, name_th, name_en) VALUES (14, 'คณะสัตวแพทยศาสตร์', 'Faculty of Veterinary Medicine');
INSERT INTO organizations (id, name_th, name_en) VALUES (15, 'คณะบริหารธุรกิจ', 'Faculty of Business Administration');
INSERT INTO organizations (id, name_th, name_en) VALUES (16, 'คณะเศรษฐศาสตร์', 'Faculty of Economics');
INSERT INTO organizations (id, name_th, name_en) VALUES (17, 'คณะสถาปัตยกรรมศาสตร์', 'Faculty of Architecture');
INSERT INTO organizations (id, name_th, name_en) VALUES (18, 'คณะการสื่อสารมวลชน', 'Faculty of Mass Communication');
INSERT INTO organizations (id, name_th, name_en) VALUES (19, 'คณะรัฐศาสตร์และรัฐประศาสนศาสตร์', 'Faculty of Political Science and Public Administration');
INSERT INTO organizations (id, name_th, name_en) VALUES (20, 'คณะนิติศาสตร์', 'Faculty of Law');
INSERT INTO organizations (id, name_th, name_en) VALUES (21, 'วิทยาลัยศิลปะ สื่อ และเทคโนโลยี', 'College of Arts, Media and Technology');
INSERT INTO organizations (id, name_th, name_en) VALUES (22, 'คณะสาธารณสุขศาสตร์', 'Faculty of Public Health');
INSERT INTO organizations (id, name_th, name_en) VALUES (23, 'วิทยาลัยการศึกษาและการจัดการทางทะเล', 'College of Education and Sea Management');
INSERT INTO organizations (id, name_th, name_en) VALUES (24, 'วิทยาลัยนานาชาตินวัตกรรมดิจิทัล', 'International College of Digital Innovation');
INSERT INTO organizations (id, name_th, name_en) VALUES (25, 'สถาบันนโยบายสาธารณะ', 'Chiang Mai University School of Public Policy');
INSERT INTO organizations (id, name_th, name_en) VALUES (26, 'สถาบันวิศวกรรมชีวการแพทย์', 'Biomedical Engineering Institute');
INSERT INTO organizations (id, name_th, name_en) VALUES (27, 'สถาบันวิจัยวิทยาศาสตร์สุขภาพ', 'Research Institute for Health Sciences');
INSERT INTO organizations (id, name_th, name_en) VALUES (30, 'บัณฑิตวิทยาลัย', 'The Graduate School');
INSERT INTO organizations (id, name_th, name_en) VALUES (51, 'สำนักหอสมุด', 'CMU Library');
INSERT INTO organizations (id, name_th, name_en) VALUES (52, 'สำนักทะเบียนและประมวลผล', 'Registration Office');
INSERT INTO organizations (id, name_th, name_en) VALUES (53, 'สำนักบริการเทคโนโลยีสารสนเทศ', 'Information Technology Services Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (54, 'สำนักบริการวิชาการ', 'University Academic Service Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (55, 'สำนักส่งเสริมศิลปวัฒนธรรม', 'Center for the Promotion of Arts and Culture');
INSERT INTO organizations (id, name_th, name_en) VALUES (56, 'สถาบันวิจัยวิทยาศาสตร์สุขภาพ', 'Institute of Health Sciences');
INSERT INTO organizations (id, name_th, name_en) VALUES (57, 'สถาบันวิจัยสังคม', 'Social Research Institute');
INSERT INTO organizations (id, name_th, name_en) VALUES (58, 'สถาบันวิจัยวิทยาศาสตร์และเทคโนโลยี', 'Science and Technology Research Institute');
INSERT INTO organizations (id, name_th, name_en) VALUES (59, 'สำนักพัฒนาคุณภาพการศึกษา', 'Office of Educational Quality Development');
INSERT INTO organizations (id, name_th, name_en) VALUES (60, 'สำนักงานมหาวิทยาลัย', 'Office of the University');
INSERT INTO organizations (id, name_th, name_en) VALUES (61, 'สำนักงานสภามหาวิทยาลัย', 'Office of the University Council');
INSERT INTO organizations (id, name_th, name_en) VALUES (62, 'ศูนย์สัตว์ทดลอง', 'Laboratory Animal Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (63, 'สถาบันวิจัยและพัฒนาพลังงานนครพิงค์', 'Energy Research and Development Institute - Nakornping');
INSERT INTO organizations (id, name_th, name_en) VALUES (64, 'ศูนย์วิจัยข้าวล้านนา', 'Lanna Rice Research and Cultural Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (65, 'สถาบันภาษา', 'Language Institute');
INSERT INTO organizations (id, name_th, name_en) VALUES (66, 'สถาบันวิจัยเทคโนโลยีหลังการเก็บเกี่ยว', 'Postharvest Technology Innovation Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (67, 'ศูนย์นวัตกรรมอาหารและบรรจุภัณฑ์', 'Food Innovation and Packaging Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (68, 'อุทยานวิทยาศาสตร์และเทคโนโลยี', 'Science and Technology Park');
INSERT INTO organizations (id, name_th, name_en) VALUES (69, 'สำนักงานการตรวจสอบภายใน', 'Internal Audit');
INSERT INTO organizations (id, name_th, name_en) VALUES (70, 'วิทยาลัยนานาชาติ (ชื่อเก่า)', 'International College (Old Name)');
INSERT INTO organizations (id, name_th, name_en) VALUES (71, 'สถาบันพิภพวิทยา', 'Institute Of Earth Sciences');
INSERT INTO organizations (id, name_th, name_en) VALUES (74, 'ศูนย์ศรีพัฒน์', 'Sriphat Medical Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (75, 'ศูนย์แก้ไขความพิการบนใบหน้าและกะโหลกศีรษะ', 'Princess Sirindhorn IT Foundation Craniofacial Center');
INSERT INTO organizations (id, name_th, name_en) VALUES (76, 'วิทยาลัยการศึกษาตลอดชีวิต', 'Lifelong Education College');
INSERT INTO organizations (id, name_th, name_en) VALUES (77, 'สถาบันวิจัยพหุศาสตร์', 'Multidisciplinary Research Institute');
INSERT INTO organizations (id, name_th, name_en) VALUES (99, 'อื่นๆ', 'Other');

INSERT INTO account_types (id, enum, name_th, name_en) VALUES (1, 'AlumAcc', 'นักศึกษาเก่า', 'Alumni Account');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (2, 'EmpResiAcc', 'บุคลากรพ้นสภาพ', 'Employee Resign Account');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (3, 'ManAcc', 'ตำแหน่งผู้บริหาร', 'Manager Account');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (4, 'MISEmpAcc', 'บุคลากร', 'MIS Employee');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (5, 'NonMISEmpAcc', 'บุคลากรนอกระบบMIS', 'Non MIS Employee');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (6, 'OrgAcc', 'หน่วยงาน', 'Organization Account');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (7, 'ProjAcc', 'โครงการ', 'Project Account');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (8, 'RetEmpAcc', 'บุคลากรเกษียณราชการ', 'Retired Employee');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (9, 'StdAcc', 'นักศึกษาปัจจุบัน', 'Student Account');
INSERT INTO account_types (id, enum, name_th, name_en) VALUES (10, 'VIPAcc', 'บุคคลสำคัญ', 'VIP Account');