INSERT INTO sys_majors (id,name_th,name_en) VALUES (10608,'วิศวกรรมคอมพิวเตอร์','Computer Engineering');
INSERT INTO sys_majors (id,name_th,name_en) VALUES (10610,'วิศวกรรมระบบสารสนเทศและเครือข่าย','Information Systems and Network Engineering');

INSERT INTO sys_category_types (name_th,name_en) VALUES ('หมวดวิชาศึกษาทั่วไป','General Education');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('หมวดวิชาเฉพาะ','Field of Specialization');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('หมวดวิชาเลือกเสรี','Free Electives');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('วิชาเอก','Major');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('วิชาโท','Minor');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('ประสบการณ์ภาคสนาม','Field Experience Training');
INSERT INTO sys_category_types (name_th,name_en) VALUES ('หลักสูตร','Curriculum');

INSERT INTO sys_curricula (major_id,name_th,short_name) VALUES (10608,'หลักสูตรวิศวกรรมคอมพิวเตอร์ หลักสูตรปรับปรุง 2563','CPE63');

INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Total',1,true,143,7,'หมายเหตุ ได้มีการจัดอบรมเตรียมความพร้อมให้แก่นักศึกษาก่อนไปสหกิจศึกษา จำนวนไม่น้อยกว่า 30 ชั่วโมง');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('1. General Education',1,false,30,1,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2. Field of Specialization',1,true,103,2,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('3 .Free Electives',1,true,6,3,'Any courses can be selected with the approval from the student’s academic advisor.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Required Courses',1,false,23,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('1.1 Learner Person',1,false,15,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('1.2 Innovative Co-creator',1,false,4,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('1.3 Active Citizen',1,false,4,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Elective from 3 Categories',1,false,7,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'3 credits must be selected from the following courses');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'3 credits must be selected from the following courses');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Learner Person',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Innovative Co-creator',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Active Citizen',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.1 Core Courses',1,false,33,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.2 Major',1,true,70,4,'Required courses in 2.2.1 and 2.2.2 must have at least 36 credit hours for course id in 300 and 400 categories with at least 18 credit hours for course id in 400 category.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.2.1 Required Courses',1,false,52,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.2.2 Major Electives',1,true,18,NULL,'There must be at least 9 credits from 261xxx.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.2.1 Required Courses',1,false,58,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.2.2 Major Electives',1,true,12,NULL,'There must be at least 9 credits from 261xxx.');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Technology for Application',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Technology and Software Methods',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Basic Structure of the Systems',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Hardware and Computer Architecture',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Field Experience Training',1,NULL,NULL,6,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('',1,NULL,NULL,NULL,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('Field Experience Training',1,NULL,NULL,6,'');
INSERT INTO sys_categories (name_en,curriculum_id,at_least,credit,category_type_id,note) VALUES ('2.3 Minor (if any)',1,true,15,5,'According to the Chiang Mai University regulation on the Minor curriculum for the Chiang Mai University student, if students choose to have a minor degree in a curriculum at the Chiang Mai university, they can register those courses not less than 15 credits with the academic advisor’s approval. Hence, the total credits for the whole curriculum is increased at least 15 credits.');

INSERT INTO sys_curriculum_questions (curriculum_id,name_en) VALUES (1,'Plan');

INSERT INTO sys_curriculum_question_choices (question_id,position,name_en) VALUES (1,1,'Normal Plan');
INSERT INTO sys_curriculum_question_choices (question_id,position,name_en) VALUES (1,2,'Cooperative Education Plan');

INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (1,2,NULL,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (1,3,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (1,4,NULL,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (2,5,NULL,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (5,6,NULL,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (5,7,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (5,8,true,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (2,9,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (6,10,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (6,11,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (7,12,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (7,13,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (9,14,false,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (9,15,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (9,16,false,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (3,17,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (3,18,NULL,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,19,NULL,1,1,1);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,20,NULL,2,1,1);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,21,NULL,1,1,2);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (18,22,NULL,2,1,2);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,23,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,24,true,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,25,true,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (19,26,true,4,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,23,true,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,24,true,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,25,true,3,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,26,true,4,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (21,27,true,5,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (20,28,false,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (20,29,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (22,28,false,1,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (22,29,false,2,NULL,NULL);
INSERT INTO sys_category_relationships (parent_category_id,child_category_id,require_all,position,question_id,choice_id) VALUES (3,30,NULL,3,NULL,NULL);

INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (18,'^...(3|4)..$',36);
INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (18,'^...4..$',18);
INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (20,'^261...$',9);
INSERT INTO sys_category_requirements (category_id,regex,credit) VALUES (22,'^261...$',9);

INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (10, '001101', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (10, '001102', 2, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (10, '001201', 1, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (3, '001101', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (3, '001102', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (10, '001225', 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (4, '001101', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (4, '001102', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (11, '204100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (11, '261111', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (11, '953111', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (12, '259192', 2, 4);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '013110', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '050106', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '176100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '201114', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '201117', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '201190', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '207109', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '207110', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '368100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '602201', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '610111', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '703103', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '751100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '851103', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (13, '852100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (8, '140104', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (8, '259191', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '201100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '203100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '211100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '462130', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '571116', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '701181', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '702101', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (14, '705191', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (15, '259194', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '011100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '109114', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '127100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '128100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '154104', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '254182', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '256131', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '259108', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '259193', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '259195', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '602102', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '801100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (16, '951100', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '206161', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '206162', 2, 1);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (49, '206161', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '206261', 1, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (50, '206162', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '207105', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '207106', 2, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '207115', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '207116', 2, 1);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (54, '207115', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '252281', 2, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '259104', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '259106', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '261208', 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (58, '206261', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '261216', 1, 2);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (17, '261306', 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (60, '206261', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (23, '261405', 2, 4);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (61, '261361', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (23, '261491', 1, 4);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (23, '261492', 2, 4);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (63, '261491', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (24, '261102', 2, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (24, '261200', 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (65, '261102', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (65, '269102', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (24, '261217', 1, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (66, '261102', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (24, '261218', 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (67, '261216', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (67, '261217', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (24, '261361', 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (68, '261200', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261103', 1, 1);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261207', 1, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (70, '261103', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261332', 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (71, '207106', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261335', 1, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (72, '261332', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (72, '269130', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261336', 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261342', 1, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (74, '261205', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (74, '261218', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (25, '261343', 1, 3);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (26, '261210', 1, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (76, '207106', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (26, '261212', 1, 2);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (26, '261214', 2, 2);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (78, '261210', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (78, '252281', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (26, '261215', 2, 2);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (26, '261304', 1, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (80, '261214', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (26, '261305', 2, 3);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (81, '261304', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (81, '269210', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (27, '261495', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261381', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261382', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261383', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261404', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (86, '261200', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261406', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (87, '261102', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261407', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (88, '261218', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261408', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261409', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (90, '261216', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (90, '261217', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261411', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261414', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (92, '261210', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261421', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (93, '261214', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (93, '261304', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261424', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261430', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261433', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (96, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261434', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (97, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261435', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (98, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261437', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (99, '261306', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (99, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261438', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (100, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261439', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261441', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261444', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (103, '261342', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261446', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (104, '261205', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (104, '261217', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261447', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (105, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261448', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261449', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (107, '261361', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261453', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261456', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261457', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261458', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261459', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261461', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (113, '261102', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (113, '269102', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (113, '229223', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261465', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (114, '259104', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261468', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261469', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261470', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261471', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261472', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261473', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261475', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261476', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (122, '252211', 'Any');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (122, '252281', 'Any');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261478', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261479', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261481', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261482', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261493', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261494', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261497', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261498', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '261499', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269421', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (132, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269430', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (133, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269431', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (134, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269432', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (135, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269433', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (136, '261335', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269441', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269461', NULL, NULL);
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (28, '269462', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (139, '261361', 'All');
INSERT INTO sys_category_courses (category_id, course_no, semester, year) VALUES (29, '261400', NULL, NULL);
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (140, '261335', 'All');
INSERT INTO sys_category_course_requisites (category_courses_id, related_course_no, requisite_type) VALUES (140, '261342', 'All');
