DROP TABLE "sys_majors" CASCADE;
DROP TABLE "sys_curricula" CASCADE;
DROP TABLE "sys_category_types" CASCADE;
DROP TABLE "sys_category_requirements";
DROP TABLE "sys_categories" CASCADE;
DROP TABLE "sys_category_relationships" CASCADE;
DROP TABLE "sys_curriculum_questions" CASCADE;
DROP TABLE "sys_curriculum_question_choices" CASCADE;
DROP TABLE "sys_category_courses" CASCADE;
DROP TABLE "sys_category_course_requisites";
DROP TABLE "sys_course_details";
DROP TABLE "student_curricula" CASCADE;
DROP TABLE "student_curriculum_courses";
DROP TABLE "student_curriculum_question_answers";
DROP TABLE "accounts";
DROP TABLE "students";
DROP TABLE "account_types";
DROP TABLE "organizations";
DROP TYPE "requisite_type";